노래 추천 화면 구현
TEAM-ALOM/plda-iOS pull request #14
Opened 2023-08-16 13:42 UTC by YugyeongChoi

## PR 요약
대기화면과 노래 추천 화면을 구현했습니다.

#### 📌 변경 사항
이미지를 많이 다운받아 Preview Assets.xcassets 파일에 넣어두었습니다.

##### ✅ PR check list
뒤로가기 버튼과 홈 버튼이 예전에 구현하던 것과 똑같이 했는데 안뜹니다ㅜ 나중에 고치겠습니다.

#### Linked Issue
close #13

#### Preview

##### WaitingView1
<img width="219" alt="스크린샷 2023-08-16 오후 9 31 13" src="https://github.com/TEAM-ALOM/plda-iOS/assets/122093721/6692b6be-2f51-4615-8acc-a58fceb8a383">

##### WaitingView2
<img width="207" alt="스크린샷 2023-08-16 오후 9 34 44" src="https://github.com/TEAM-ALOM/plda-iOS/assets/122093721/5e122b57-0060-47c8-a6c7-24a2873ca29b">

##### RecommendView
<img width="285" alt="스크린샷 2023-08-16 오후 10 31 36" src="https://github.com/TEAM-ALOM/plda-iOS/assets/122093721/5e49c195-b3f7-4e4d-9b74-234a1ada4861">

2023-08-17 06:30 UTC, mooyoung2309 requested changes
View의 변경사항을 확인했고, 수정사항이 있으니 push 이후에 다시 reveiew어 등록해주시면 그때 다시 리뷰하겠습니다 : D

2023-08-17 06:30 UTC, mooyoung2309 commented on Targets/Plda/Sources/Views/WaitingView1.swift
> +
p1;

네임이름 뒤에 숫자를 붙이는 경우는 피하는게 좋습니다. 숫자를 사용하는 것은 아주 특별한 경우가 있는걸로 알고있습니다. 아마 이경우는 조금 더 길더라도 표현할 수 있어보이네요.

2023-08-17 06:30 UTC, mooyoung2309 commented on Targets/Plda/Sources/Views/WaitingView1.swift
> +                .font(.Bold16)
p1;

이부분 제가 놓친 부분이긴 한데 swift에서 프로퍼티는 카멜 케이스의 규칙을 사용하고 있어요. 따라서 , 디자인 시스템을 변경해주셨으면 합니다!

2023-08-17 06:30 UTC, mooyoung2309 commented on Targets/Plda/Resources/Preview Content/Preview Assets.xcassets/heart.imageset/Contents.json
> +    },
p1;

파일 이름은 한글로 하면 오류가 발생할 가능성이 있습니다. 또한 띄어쓰기는 네임을 헷갈리게 하기 때문에 스네이크 케이스 or 카멜, 파스칼을 정해서 하는게 좋습니다. 역시 카멜 케이스를 추천드려요

2023-08-17 06:30 UTC, mooyoung2309 commented on Targets/Plda/Sources/Views/WaitingView2.swift
> +        .background(Image("background")
p4;

tuist 라이브러리는 이미지 접근을 도와주고 있습니다. 아마도 Tuist Image 접근 이라고 검색해서 변경해보면 좋을듯 싶습니다.

2023-08-24 13:43 UTC, YugyeongChoi commented on Targets/Plda/Sources/Views/WaitingView2.swift
> +        .background(Image("background")
아직 이것은 해결 안 한 상태입니다! 리뷰어 다시 등록하고 수정하겠습니다!!

2023-08-24 13:52 UTC, mooyoung2309 approved these changes
반영해주시고 각자 머지시키면 될것같아요!

2023-08-24 14:10 UTC, YugyeongChoi commented
넵 감사합니다!

2023-08-24 14:10 UTC, merged